{{- if .Values.ingress.enabled -}}
{{- $fullName := include "graphite.fullname" . -}}
{{- $name := .Values.service.name -}}
{{- $ingressPath := .Values.ingress.path -}}
{{- $releaseName := .Release.Name -}}
{{- $data := . -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ include "graphite.name" $data }}
    chart: {{ include "graphite.chart" $data }}
    release: {{ $releaseName }}
    heritage: {{ $data.Release.Service }}
  {{- with $data.Values.ingress.annotations }}
  annotations:
    {{- toYaml $data | nindent 4 }}
  {{- end }}
spec:
  rules:
  {{- range $data.Values.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: http
  {{- end }}
{{- end }}
